server:
  servlet:
    session:
      # 设置session超时时间(最小是1分钟 )
      timeout: 600
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/framework-demo?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam引擎
  redis:
    host: 127.0.0.1
    port: 6379
  session:
#    设置spring-session存储类型
    store-type: redis

#  #ThymeLeaf配置
#  thymeleaf:
#    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
#    mode: HTML5
#    #编码 可不用配置
#    encoding: UTF-8
#    #内容类别,可不用配置
#    servlet:
#      content-type: text/html
#    #开发配置为false,避免修改模板还要重启服务器
#    cache: false
#    #配置模板路径，默认是templates，可以不用配置
#    prefix: classpath:/templates

#security:
#  basic:
#    enabled: false

#应用级配置
earthchen:
  security:
    browser:
##      配置自定义登录页,不配置则为默认登录页
#      loginPage: /demo-signIn.html
      # 配置自定义注册页
      registerPage: /demo-signUp.html
      # 自定义退出登录成功页
#      signOutUrl: /demo-logout.html


    validateCode:
      imageCode:
#         设置图形验证码的长度为6，不配置则为默认验证码属性
        length: 4
        width: 67
#        url: /user,/user/*
    social:
      qq:
        app-id: 100550231
        app-secret: 4444444444444
        # 设置providerId
        providerId: callback.do
        # 将社交登录social前缀的/auth改为以下内容
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4

      # 最终url为/social-auth/callback.do
      filterProcessesUrl: /qqLogin
    # 配置oauth2
    oauth2:
      # 对多个应用进行配置
      clients[0]:
        clientId: earthchen0
        clientSecret: earthchensecret0
        accessTokenValidateSeconds: 3600
      clients[1]:
        clientId: earthchen1
        clientSecret: earthchensecret1
        accessTokenValidateSeconds: 7200
      storeType: jwt








